# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 10, 711, 541))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.productLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.productLabel.setStyleSheet("font: 8pt \"Poppins\";")
        self.productLabel.setObjectName("productLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.productLabel)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.quantityLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.quantityLabel.setStyleSheet("font: 8pt \"Poppins\";")
        self.quantityLabel.setObjectName("quantityLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.quantityLabel)
        self.quantityLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.quantityLineEdit.setStyleSheet("font: 8pt \"Poppins\";")
        self.quantityLineEdit.setObjectName("quantityLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.quantityLineEdit)
        self.discountLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.discountLabel.setStyleSheet("font: 8pt \"Poppins\";")
        self.discountLabel.setObjectName("discountLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.discountLabel)
        self.comboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.pushButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton.setStyleSheet("font: 8pt \"Poppins\";")
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_2.setStyleSheet("font: 8pt \"Poppins\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButton_2)
        self.listView = QtWidgets.QListView(self.formLayoutWidget)
        self.listView.setStyleSheet("font: 8pt \"Poppins\";")
        self.listView.setObjectName("listView")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.listView)
        self.frame = QtWidgets.QFrame(self.formLayoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.frame)
        self.productLabel_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.productLabel_2.setStyleSheet("font: 8pt \"Poppins\";")
        self.productLabel_2.setObjectName("productLabel_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.productLabel_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.productLabel.setText(_translate("MainWindow", "Product"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Minyak Kita 750 ml"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Beras Bulog 5 kg"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Kecap Wakanda"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Gula Hytam 1 kg"))
        self.quantityLabel.setText(_translate("MainWindow", "Quantity"))
        self.discountLabel.setText(_translate("MainWindow", "Discount"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "5%"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "10%"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "15%"))
        self.pushButton.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_2.setText(_translate("MainWindow", "Clear"))
        self.productLabel_2.setText(_translate("MainWindow", "Total "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
